version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/path/to/certs:/etc/nginx/certs:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: on-failure

  nginx-proxy-encrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/path/to/certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    restart: on-failure

  dockerhub-hook:
    image: maccyber/micro-dockerhub-hook
    volumes:
      - "/scripts:/src/scripts"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/docker-compose:/docker-compose"
    environment:
      - VIRTUAL_HOST=dockerhub.jedthompson.co.uk
      - LETSENCRYPT_HOST=dockerhub.jedthompson.co.uk
      - LETSENCRYPT_EMAIL=jedster1111@hotmail.co.uk
      - TOKEN
    restart: on-failure

  pollingapp:
    image: jedster1111/pollingapp
    volumes:
      - "/database:/usr/src/app/database"
    environment:
      - VIRTUAL_HOST=pollingapp.jedthompson.co.uk
      - LETSENCRYPT_HOST=pollingapp.jedthompson.co.uk
      - LETSENCRYPT_EMAIL=jedster1111@hotmail.co.uk
      - CLIENT_ID
      - CLIENT_SECRET
      - SECRET_KEY
      - URL
    restart: on-failure
    container_name: pollingapp

  jenkins:
    image: jedster1111/jenkinsdocker
    volumes:
      - "/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=jenkins.jedthompson.co.uk
      - LETSENCRYPT_HOST=jenkins.jedthompson.co.uk
      - LETSENCRYPT_EMAIL=jedster1111@hotmail.co.uk
      - VIRTUAL_PORT=8080

    user: root
    privileged: true
    restart: on-failure
