version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /path/to/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: on-failure

  nginx-proxy-encrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /path/to/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    restart: on-failure

  pollingapp:
    image: jedster1111/pollingapp
    environment:
      - VIRTUAL_HOST=jedthompson.co.uk,www.jedthompson.co.uk
      - LETSENCRYPT_HOST=jedthompson.co.uk,www.jedthompson.co.uk
      - LETSENCRYPT_EMAIL=jedster1111@hotmail.co.uk
      - CLIENT_ID
      - CLIENT_SECRET
      - SECRET_KEY
      - URL
    restart: on-failure

  jenkins:
    image: jedster1111/jenkinsdocker
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=jenkins.jedthompson.co.uk
      - LETSENCRYPT_HOST=jenkins.jedthompson.co.uk
      - LETSENCRYPT_EMAIL=jedster1111@hotmail.co.uk
      - VIRTUAL_PORT=8080
    user: root
    privileged: true
    restart: on-failure

volumes:
  jenkins_home:
